# Movie Recomendation System(LightFM & Colaborative Filtering)

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats

In [ ]:
movie = pd.read_csv('../data/raw/movie.csv')
rating = pd.read_csv('../data/raw/rating.csv')

In [3]:
movie.sample(5)

       movieId                                title                   genres
2249      2334                    Siege, The (1998)          Action|Thriller
24691   116791                        Callan (1974)                 Thriller
3587      3678  Man with the Golden Arm, The (1955)                    Drama
7242      7354             Mad Dog and Glory (1993)     Comedy|Drama|Romance
17842    89607                     Nightmare (1964)  Horror|Mystery|Thriller

In [4]:
movie.info()

<class 'pandas.DataFrame'>
RangeIndex: 27278 entries, 0 to 27277
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  27278 non-null  int64
 1   title    27278 non-null  str
 2   genres   27278 non-null  str
dtypes: int64(1), str(2)
memory usage: 639.5 KB

In [5]:
rating.sample(5)

          userId  movieId  rating            timestamp
7593328    52321     3252     4.0  2001-09-15 20:37:27
6290697    43221      234     3.0  2003-08-10 21:01:26
10948165   75713      848     5.0  2000-01-19 19:12:43
5978080    41193     1064     2.0  2000-12-26 17:41:26
10844785   74986      316     4.0  1996-07-10 05:54:46

In [6]:
rating.info(show_counts=True)

<class 'pandas.DataFrame'>
RangeIndex: 20000263 entries, 0 to 20000262
Data columns (total 4 columns):
 #   Column     Non-Null Count     Dtype
---  ------     --------------     -----
 0   userId     20000263 non-null  int64
 1   movieId    20000263 non-null  int64
 2   rating     20000263 non-null  float64
 3   timestamp  20000263 non-null  str
dtypes: float64(1), int64(2), str(1)
memory usage: 610.4 MB