In [2]:
import pandas as pd
import numpy as np
import os

In [3]:
ratings = pd.read_csv('../data/preprocessed/ratings_cleaned.csv')
movies = pd.read_csv('../data/preprocessed/movies_cleaned.csv')

In [24]:
ratings.tail(350000)

        userId  movieId  rating            timestamp
639523   89575     4029     3.5  2004-04-05 00:27:17
639524   89575     4034     4.5  2004-04-05 00:06:55
639525   89575     4077     4.0  2004-04-05 00:26:12
639526   89575     4143     2.0  2001-02-12 05:44:14
639527   89575     4148     3.0  2004-04-04 23:22:35
...        ...      ...     ...                  ...
989518  138489     2959     4.5  2012-11-15 14:35:14
989519  138489     3671     4.0  2012-11-15 14:18:27
989520  138489     4973     4.0  2012-11-15 14:35:24
989521  138489     5291     4.5  2012-11-15 14:35:58
989522  138489    58559     4.0  2012-11-15 14:21:49

[350000 rows x 4 columns]

In [4]:
user_item_matrix = ratings.pivot(
    index='movieId',
    columns='userId',
    values='rating'
).fillna(0)

In [5]:
user_item_matrix

userId,36,90,118,120,129,140,162,196,199,202,...,138315,138320,138333,138345,138393,138399,138402,138409,138449,138489
movieId,,,,,,,,,,,,,,,,,,,,,
1,0.0,3.5,0.0,0.0,4.0,4.0,3.0,0.0,4.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,1.0,3.0,0.0,0.0,0.0,0.0,0.0,...,0.0,4.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118930,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
119141,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
119145,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
119155,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
120635,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
user_item_matrix.shape

(9222, 6914)

In [7]:
output_dir = '../data/preprocessed'

In [8]:
os.makedirs(output_dir, exist_ok=True)

In [9]:
output_path = f'{output_dir}/user_item_matrix_baseline.pkl'
user_item_matrix.to_pickle(output_path)

In [10]:
output_path

'../data/preprocessed/user_item_matrix_baseline.pkl'

## LightGBM preprocessing

In [11]:
from sklearn.preprocessing import MultiLabelBinarizer
import ast

In [12]:
movies['year'] = movies['title'].str.extract(r'\((\d{4})\)').astype(float)
movies['year'] = movies['year'].fillna(movies['year'].median())

In [13]:
movies['genres'] = movies['genres'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)

In [14]:
mlb = MultiLabelBinarizer()

In [15]:
genre_matrix = mlb.fit_transform(movies['genres'])

In [16]:
genre_df = pd.DataFrame(genre_matrix, columns=[f"gen_{c}" for c in mlb.classes_])

In [17]:
movies_features = pd.concat([movies[['movieId', 'year']], genre_df], axis=1)

In [18]:
movies_features.sample(5)

,movieId,year,gen_Action,gen_Adventure,gen_Animation,gen_Children,gen_Comedy,gen_Crime,gen_Documentary,gen_Drama,...,gen_Film-Noir,gen_Horror,gen_IMAX,gen_Musical,gen_Mystery,gen_Romance,gen_Sci-Fi,gen_Thriller,gen_War,gen_Western
540,588,1992.0,0,1,1,1,1,0,0,0,...,0,0,0,1,0,0,0,0,0,0
867,1029,1941.0,0,0,1,1,0,0,0,1,...,0,0,0,1,0,0,0,0,0,0
7366,51357,1995.0,0,0,0,0,0,1,0,1,...,0,0,0,0,0,0,0,1,0,0
652,747,1996.0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1101,1310,1996.0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [19]:
def generate_negative_samples(ratings, movies_df, ratio=4):
    """
    For each real interaction (watched movie), generate random negative samples 
    (movies the user has NOT watched) to teach the model what the user ignores.
    """
    user_ids = ratings['userId'].unique()
    movie_ids = movies_df['movieId'].unique()
    
    negatives = []
    
    for u_id in user_ids:
        # Movies the user has already watched (positive interactions)
        seen_movies = set(ratings[ratings['userId'] == u_id]['movieId'])
        
        # Movies the user has NEVER watched
        unseen_movies = list(set(movie_ids) - seen_movies)
        
        # Randomly select negative samples (e.g., 4 times the number of positive samples)
        num_neg = min(len(seen_movies) * ratio, len(unseen_movies))
        neg_samples = np.random.choice(unseen_movies, num_neg, replace=False)
        
        for m_id in neg_samples:
            negatives.append([u_id, m_id, 0]) # 0 represents the "not watched" target
            
    return pd.DataFrame(negatives, columns=['userId', 'movieId', 'target'])

In [20]:
# Create positive samples from actual user ratings
ratings['user_mean'] = ratings.groupby('userId')['rating'].transform('mean')

# We consider that a film is positiv only when rating is higher than user avg 
good_ratings = ratings[ratings['rating'] >= ratings['user_mean']]

positive_samples = good_ratings[['userId', 'movieId']].copy()
positive_samples['target'] = 1

In [21]:
# Generate negative samples
negative_samples = generate_negative_samples(ratings, movies)

In [22]:
# Combine positive and negative samples into one dataset, then shuffle it
full_dataset = pd.concat([positive_samples, negative_samples], axis=0).sample(frac=1).reset_index(drop=True)

In [23]:
# Merge the interaction dataset with the movie features (year and genres)
final_train_df = full_dataset.merge(movies_features, on='movieId', how='left')

In [24]:
# Save the final datasets for the LightGBM model training phase
final_train_df.to_pickle('../data/preprocessed/train_data_lgbm.pkl')
movies_features.to_pickle('../data/preprocessed/movies_features_lgbm.pkl')

In [1]:
final_train_df.sample(10)

NameError: name 'final_train_df' is not defined

In [26]:
final_train_df.shape

(4440630, 23)

In [27]:
final_train_df['userId'].unique()

array([ 95501,  68258, 130812, ...,  71347,  55667,  15183], shape=(6914,))